### ISSUE TITLE
Panoptic Label of the Dataset

### ISSUE THREAD

**Issue by hphnngcquan** [PRBonn/nuscenes2kitti#3]
Dear @rmarcuzzi 

Many thanks for this great work,
But I would like to ask something about the sem_lab and pan_lab variables:

![image](https://github.com/user-attachments/assets/6c27c13f-ad56-4c87-8132-d85d91b815cc)

Are the sem_lab and sem_lab2 (generated from pan_lab) identical?
I reckon that you did not use sem_lab2 in this code, is there a reason?

**Comment by rmarcuzzi** [comment]
Hi!

sem_lab comes from the semantic labels of nucenes while sem_lab2 comes from the panoptic labels and they're not identical.
We decided to use the semantic labels but you could also use the semantic labels that come from the panoptic version.

**Comment by hphnngcquan** [comment]
Thank you for your reply
